const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding VMANOUS MySQL database...');

  // 1. Seed Summits / Programs
  await prisma.summit.deleteMany();
  await prisma.summit.createMany({
    data: [
      {
        id: 1,
        title: 'AI SUMMIT WORKSHOP 2030',
        subtitle: 'Generative AI, Prompt Engineering & Agentic LLMs',
        type: 'Flagship Event',
        college: 'G H RAISONI',
        address: 'Shradhhaa park Nagpur',
        price: 1999,
        originalPrice: 4999,
        taxRate: 18,
        taxMode: 'Exclusive',
        processingFee: 0,
        processingFeeType: 'Fixed',
        duration: '1-Day Live Workshop',
        time: '10:00 AM - 05:00 PM',
        startDate: '2026-08-30',
        endDate: '2026-08-30',
        date: '30-08-2026',
        seatCapacity: 100,
        status: 'Registration Open',
        features: ['Providing Certificate']
      },
      {
        id: 2,
        title: 'Workshop Aegentic ai',
        subtitle: 'Full-Stack AI & RAG Architecture Engineering',
        type: 'Campus Workshop',
        college: 'KDK',
        address: 'Sakardhara',
        price: 2999,
        originalPrice: 6999,
        taxRate: 18,
        taxMode: 'Exclusive',
        processingFee: 0,
        processingFeeType: 'Fixed',
        duration: '2-Day Live Workshop',
        time: '10:00 AM - 05:00 PM',
        startDate: '2026-08-20',
        endDate: '2026-08-21',
        date: '20-08-2026',
        seatCapacity: 10,
        status: 'Filling Fast',
        features: ['Expert Mentorship']
      },
      {
        id: 3,
        title: 'Data Science',
        subtitle: 'Machine Learning, PyTorch & Deep Learning Models',
        type: 'Flagship Event',
        college: 'D Y PATIL',
        address: 'Akurdi pune',
        price: 1999,
        originalPrice: 4999,
        taxRate: 18,
        taxMode: 'Exclusive',
        processingFee: 0,
        processingFeeType: 'Fixed',
        duration: '2-Day Live Workshop',
        time: '10:00 AM - 05:00 PM',
        startDate: '2026-08-20',
        endDate: '2026-08-25',
        date: 'Aug 20-25, 2026',
        seatCapacity: 150,
        status: 'Registration Open',
        features: ['Providing Certificate', '123456']
      },
      {
        id: 4,
        title: 'AI Summit Workshop 2026',
        subtitle: 'Machine Learning, PyTorch & Deep Learning Models',
        type: 'Flagship Event',
        college: 'INDIAN INSTITUTE OF TECHNOLOGY',
        address: 'Victor Menezes Convention Centre',
        price: 2999,
        originalPrice: 6999,
        taxRate: 18,
        taxMode: 'Exclusive',
        processingFee: 0,
        processingFeeType: 'Fixed',
        duration: '3-Day Hands-on Summit',
        time: '09:00 AM - 05:00 PM',
        startDate: '2026-11-14',
        endDate: '2026-11-16',
        date: 'Nov 14-16, 2026',
        seatCapacity: 100,
        status: 'Registration Open',
        features: ['Hands-on GPU Labs']
      },
      {
        id: 5,
        title: 'AI Summit Workshop 2026',
        subtitle: 'Full-Stack AI & RAG Architecture Engineering',
        type: 'Flagship Event',
        college: 'DELHI TECHNOLOGICAL UNIVERSITY',
        address: 'Delhi Campus Auditorium',
        price: 1999,
        originalPrice: 4999,
        taxRate: 18,
        taxMode: 'Exclusive',
        processingFee: 0,
        processingFeeType: 'Fixed',
        duration: '2-Day National Bootcamp',
        time: '10:00 AM - 04:00 PM',
        startDate: '2026-12-12',
        endDate: '2026-12-13',
        date: 'Dec 12-13, 2026',
        seatCapacity: 100,
        status: 'Registration Open',
        features: ['Full Stack AI']
      }
    ]
  });

  // 2. Seed Applications & Payment Transactions
  await prisma.application.deleteMany();
  await prisma.paymentTransaction.deleteMany();

  const applicationsData = [
    {
      id: 'app_101',
      studentName: 'Ujwal Durgaprasad Bramhnote',
      email: 'ujwalbramhnote@gmail.com',
      phone: '+91 9876543210',
      programTitle: 'AI SUMMIT WORKSHOP 2030',
      collegeName: 'G H RAISONI',
      venueLocation: 'Shradhhaa park Nagpur',
      branch: 'Computer Science & Engineering',
      year: '3rd Year',
      degree: 'B.Tech',
      marksTenth: '88.5%',
      marksTwelfth: '85.0%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124871',
      amountPaid: 2359.00,
      baseAmount: 1999.15,
      gstAmount: 359.85,
      platformFee: 99.00,
      passCode: 'PASS-6816',
      summitId: 1
    },
    {
      id: 'app_102',
      studentName: 'Aarav Sharma',
      email: 'aarav.sharma@example.com',
      phone: '+91 9876543210',
      programTitle: 'AI SUMMIT WORKSHOP 2030',
      collegeName: 'G H RAISONI',
      venueLocation: 'Shradhhaa park Nagpur',
      branch: 'Computer Science & Engineering',
      year: '3rd Year',
      degree: 'B.Tech',
      marksTenth: '92.0%',
      marksTwelfth: '91.4%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124872',
      amountPaid: 2359.00,
      baseAmount: 1999.15,
      gstAmount: 359.85,
      platformFee: 99.00,
      passCode: 'PASS-GHRCEM-801',
      summitId: 1
    },
    {
      id: 'app_103',
      studentName: 'Priya Patel',
      email: 'priya.patel@example.com',
      phone: '+91 9823456789',
      programTitle: 'Workshop Aegentic ai',
      collegeName: 'KDK',
      venueLocation: 'Sakardhara',
      branch: 'Artificial Intelligence & Data Science',
      year: '4th Year',
      degree: 'B.Tech',
      marksTenth: '82.0%',
      marksTwelfth: '80.5%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124873',
      amountPaid: 2359.00,
      baseAmount: 1999.15,
      gstAmount: 359.85,
      platformFee: 99.00,
      passCode: 'PASS-KDK-802',
      summitId: 2
    },
    {
      id: 'app_104',
      studentName: 'Ananya Verma',
      email: 'ananya.v@example.com',
      phone: '+91 9654321098',
      programTitle: 'AI Summit Workshop 2026',
      collegeName: 'INDIAN INSTITUTE OF TECHNOLOGY',
      venueLocation: 'Victor Menezes Convention Centre',
      branch: 'Computer Science',
      year: '3rd Year',
      degree: 'B.Tech',
      marksTenth: '95.6%',
      marksTwelfth: '94.2%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124874',
      amountPaid: 2359.00,
      baseAmount: 1999.15,
      gstAmount: 359.85,
      platformFee: 99.00,
      passCode: 'PASS-IITB-804',
      summitId: 4
    },
    {
      id: 'app_105',
      studentName: 'Rohan Mehta',
      email: 'rohan.mehta@example.com',
      phone: '+91 9432109876',
      programTitle: 'Data Science',
      collegeName: 'D Y PATIL',
      venueLocation: 'Akurdi pune',
      branch: 'Information Technology',
      year: '2nd Year',
      degree: 'B.Tech',
      marksTenth: '87.0%',
      marksTwelfth: '84.0%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124875',
      amountPaid: 5902.00,
      baseAmount: 5001.69,
      gstAmount: 900.31,
      platformFee: 99.00,
      passCode: 'PASS-DYP-805',
      summitId: 3
    },
    {
      id: 'app_106',
      studentName: 'Sneha Kulkarni',
      email: 'sneha.k@example.com',
      phone: '+91 9765432109',
      programTitle: 'AI Summit Workshop 2026',
      collegeName: 'DELHI TECHNOLOGICAL UNIVERSITY',
      venueLocation: 'Delhi Campus Auditorium',
      branch: 'Computer Science',
      year: '3rd Year',
      degree: 'B.Tech',
      marksTenth: '91.2%',
      marksTwelfth: '89.0%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124876',
      amountPaid: 5902.00,
      baseAmount: 5001.69,
      gstAmount: 900.31,
      platformFee: 99.00,
      passCode: 'PASS-DTU-806',
      summitId: 5
    },
    {
      id: 'app_107',
      studentName: 'Vikramaditya Singh',
      email: 'vikram.singh@example.com',
      phone: '+91 9812345678',
      programTitle: 'Workshop Aegentic ai',
      collegeName: 'KDK',
      venueLocation: 'Sakardhara',
      branch: 'Data Science',
      year: '4th Year',
      degree: 'B.Tech',
      marksTenth: '89.0%',
      marksTwelfth: '87.5%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124877',
      amountPaid: 5902.00,
      baseAmount: 5001.69,
      gstAmount: 900.31,
      platformFee: 99.00,
      passCode: 'PASS-KDK-807',
      summitId: 2
    },
    {
      id: 'app_108',
      studentName: 'Neha Sharma',
      email: 'neha.s@example.com',
      phone: '+91 9923456781',
      programTitle: 'Data Science',
      collegeName: 'D Y PATIL',
      venueLocation: 'Akurdi pune',
      branch: 'Artificial Intelligence',
      year: '2nd Year',
      degree: 'B.Tech',
      marksTenth: '93.5%',
      marksTwelfth: '92.1%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124878',
      amountPaid: 2359.00,
      baseAmount: 1999.15,
      gstAmount: 359.85,
      platformFee: 99.00,
      passCode: 'PASS-DYP-808',
      summitId: 3
    },
    {
      id: 'app_109',
      studentName: 'Aditya Deshmukh',
      email: 'aditya.d@example.com',
      phone: '+91 9834567892',
      programTitle: 'AI SUMMIT WORKSHOP 2030',
      collegeName: 'G H RAISONI',
      venueLocation: 'Shradhhaa park Nagpur',
      branch: 'Computer Engineering',
      year: '3rd Year',
      degree: 'B.Tech',
      marksTenth: '86.4%',
      marksTwelfth: '84.8%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124879',
      amountPaid: 2359.00,
      baseAmount: 1999.15,
      gstAmount: 359.85,
      platformFee: 99.00,
      passCode: 'PASS-GHRCEM-809',
      summitId: 1
    },
    {
      id: 'app_110',
      studentName: 'Riya Sen',
      email: 'riya.sen@example.com',
      phone: '+91 9745678903',
      programTitle: 'AI Summit Workshop 2026',
      collegeName: 'INDIAN INSTITUTE OF TECHNOLOGY',
      venueLocation: 'Victor Menezes Convention Centre',
      branch: 'Information Technology',
      year: '4th Year',
      degree: 'B.Tech',
      marksTenth: '90.1%',
      marksTwelfth: '88.9%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124880',
      amountPaid: 5359.00,
      baseAmount: 4541.53,
      gstAmount: 817.47,
      platformFee: 99.00,
      passCode: 'PASS-IITB-810',
      summitId: 4
    },
    {
      id: 'app_111',
      studentName: 'Tanmay Joshi',
      email: 'tanmay.j@example.com',
      phone: '+91 9656789014',
      programTitle: 'AI Summit Workshop 2026',
      collegeName: 'DELHI TECHNOLOGICAL UNIVERSITY',
      venueLocation: 'Delhi Campus Auditorium',
      branch: 'Computer Science',
      year: '3rd Year',
      degree: 'B.Tech',
      marksTenth: '87.9%',
      marksTwelfth: '86.2%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Paid',
      verificationStatus: 'Verified',
      transactionId: 'TXN_998124881',
      amountPaid: 5359.00,
      baseAmount: 4541.53,
      gstAmount: 817.47,
      platformFee: 99.00,
      passCode: 'PASS-DTU-811',
      summitId: 5
    },
    {
      id: 'app_112',
      studentName: 'Kunal Patil',
      email: 'kunal.p@example.com',
      phone: '+91 9567890125',
      programTitle: 'AI SUMMIT WORKSHOP 2030',
      collegeName: 'G H RAISONI',
      venueLocation: 'Shradhhaa park Nagpur',
      branch: 'Computer Science',
      year: '3rd Year',
      degree: 'B.Tech',
      marksTenth: '85.0%',
      marksTwelfth: '83.0%',
      selfiePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
      paymentStatus: 'Failed',
      paymentFailureReason: 'Bank Server Timeout / Payment Cancelled',
      verificationStatus: 'Pending Audit',
      transactionId: 'TXN_FAIL_99182',
      amountPaid: 0,
      baseAmount: 0,
      gstAmount: 0,
      platformFee: 0,
      passCode: null,
      summitId: 1
    }
  ];

  await prisma.application.createMany({ data: applicationsData });

  // 3. Seed Students
  await prisma.student.deleteMany();
  const paidApps = applicationsData.filter(a => a.paymentStatus === 'Paid');
  await prisma.student.createMany({
    data: paidApps.map(a => ({
      name: a.studentName,
      email: a.email,
      phone: a.phone,
      collegeName: a.collegeName,
      branch: a.branch,
      year: a.year,
      passCode: a.passCode
    }))
  });

  console.log('Seeding completed successfully with 11 paid applications & students!');
}

main()
  .catch((e) => {
    console.error('Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
